export const COLOR_CHAT_BACKGROUND = '#f7f7f7';
export const COLOR_CHAT_BACKGROUND_SHADOW = 'rgba(77, 56, 135, .5)';
export const COLOR_CHAT_THEIRS_BACKGROUND = '#4d38a3';
export const COLOR_CHAT_THEIRS_TEXT = '#fff';
export const COLOR_CHAT_MINE_BACKGROUND = '#406e7d';
export const COLOR_CHAT_MINE_TEXT = '#fff';
export const COLOR_SCROLLBAR_TRACK = '#f1f1f1';
export const COLOR_SCROLLBAR_THUMB = '#8c97bd';
export const COLOR_SCROLLBAR_THUMB_HOVER = '#555';
